server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?autoreconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1120
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml

